MealRec+L:
  data_path: './datasets'
  batch_size_train: 1024
  batch_size_test: 512
  topk: [10, 20, 40, 80]
  neg_num: 1

  aug_type: "ED"
  ed_interval: 1
  embedding_sizes: [64] 
  num_layerss: [2]
  lrs: [1.0e-3]
  item_level_ratios: [0.05]
  bundle_level_ratios: [0.05]
  bundle_agg_ratios: [0]
  user_agg_ratios: [0]

  l2_regs: [4.0e-5]
  c_lambdas: [0.25]
  c_temps: [0.2]

  epochs: 100
  test_interval: 3

MealRec+H:
  data_path: './datasets'
  batch_size_train: 1024
  batch_size_test: 512
  topk: [10, 20, 40, 80]
  neg_num: 1

  aug_type: "ED"
  ed_interval: 1
  embedding_sizes: [64]
  num_layerss: [2]
  lrs: [1.0e-3]
  item_level_ratios: [0.2]
  bundle_level_ratios: [0.2]
  bundle_agg_ratios: [0.1]

  l2_regs: [1.0e-5] 
  c_lambdas: [0.25]
  c_temps: [0.2]

  epochs: 150
  test_interval: 10
